### ISSUE TITLE
Midi bus versus Processing 3

### ISSUE THREAD

**Issue by StanLepunK** [sparks/themidibus#15]
Hello, I try Midi Bus with the last version of Processing 3.0b5 and that's don't work.
Processinf return
`````NoSuchMethodError: You may be using a library that's incompatible with this version of Processing. `````

Sure you know that :)

**Comment by sparks** [comment]
Hi @StanLepunK, I've just updated to version 008 which I think should work with processing 3.0

You can download the precompiled version here to try it out http://smallbutdigital.com/releases/themidibus/themidibus-latest.zip

Please reopen this if it's still not working for you

**Comment by StanLepunK** [comment]
I check taht I soon as possible. Thx for your work !!!!!!
